# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'unit2-flix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for unit2-flix
  pod 'AlamofireImage'

end
